In [ ]:
print("my name jeff")

In [ ]:
import os
import urllib.parse
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv

# 1. Load the hidden variables from the .env file
load_dotenv()


# 2. Build your connection engine
DATABASE_URL = os.getenv("DATABASE_URL")
engine = create_engine(DATABASE_URL)

# 3.

In [2]:
from sqlalchemy import text

# 1. Test using a clean SQLAlchemy connection block
try:
    with engine.connect() as connection:
        # Run a lightweight raw SQL query to test responsiveness
        result = connection.execute(text("SELECT NOW();"))
        db_time = result.scalar()
        
    print("🚀 CONNECTION SUCCESSFUL!")
    print(f"PostgreSQL server time: {db_time}")

except Exception as e:
    print("❌ CONNECTION FAILED!")
    print(f"Error details: {e}")

🚀 CONNECTION SUCCESSFUL!
PostgreSQL server time: 2026-08-25 12:14:27.777387+08:00

In [54]:
# 1. Write the SQL query to pull 5 items from the movies table
query = "SELECT DISTINCT birthday FROM people LIMIT 10;"

try:
    # 2. Use Pandas to run the query and create a DataFrame
    df = pd.read_sql(query, con=engine)
    
    # 3. Print success confirmation and dimensions
    print(f"🎉 Pandas loaded {df.shape[0]} rows and {df.shape[1]} columns successfully!")
    
    # 4. Display the data grid cleanly
    display(df)

except Exception as e:
    print("❌ Failed to pull data into Pandas.")
    print("Error details:", e)

🎉 Pandas loaded 1 rows and 1 columns successfully!

  birthday
0     None

In [4]:
df.info

<bound method DataFrame.info of    movie_id     imdb_id                    title           original_title  \
0      1574   tt0299658                  Chicago                  Chicago
1      1590   tt0424908        Copying Beethoven        Copying Beethoven
2      1644   tt0108473            The Vanishing            The Vanishing
3   1375646  tt34385135                   Colony                       군체
4   1108427  tt27419466                    Moana                    Moana
5     82023   tt2080323             Hotel Desire             Hotel Desire
6   1284465  tt32273171  The Death of Robin Hood  The Death of Robin Hood
7    697117  tt12788048                Distorção                Distorção
8    295803   tt4968004           Dança Prosaica           Dança Prosaica

                                tagline  \
0  If you can't be famous, be infamous.
1
2     Obsession is the ultimate weapon.
3                     Survive the hive.
4     The ocean chose her for a reason.
5
6                       He was no hero.
7
8

                                            overview release_date    status  \
0  Murderesses Velma Kelly and Roxie Hart find th...   2002-12-10  Released
1  A fictionalised exploration of Beethoven's lif...   2006-09-10  Released
2  The boyfriend of an abducted woman never gives...   1993-02-05  Released
3  Professor Se-jeong is thrust into a bloody nig...   2026-05-21  Released
4  Teenage Moana answers the Ocean's call and, fo...   2026-07-08  Released
5  Antonia is a single mother who works as a hote...   2011-12-07  Released
6  Grappling with his past after a life of crime ...   2026-06-18  Released
7  Days seem calm on Socorro’s apartment, where T...   2019-08-16  Released
8               Three friends go to an unsual party.   2014-09-29  Released

   runtime     budget  ...  vote_count  adult  video  \
0      113   45000000  ...        2964  False  False
1      104   11000000  ...         190  False  False
2      109          0  ...         577  False  False
3      123          0  ...         591  False  False
4      115  250000000  ...         225  False  False
5       38     230758  ...         159  False  False
6      123   25000000  ...         243  False  False
7       15          0  ...           0  False  False
8        8          0  ...           1  False  False

                                            homepage  \
0
1
2
3                 https://wellgousa.com/films/colony
4               https://movies.disney.com/moana-2026
5
6  https://a24films.com/films/the-death-of-robin-...
7
8

                        poster_path                     backdrop_path  \
0  /3ED8cWCXY9zkx77Sd0N5qMbsdDP.jpg  /euxYhuuJjChU755u2YHj0ZPjww3.jpg
1  /xplAbPXhZF9B3H4OnhjQsEKUESe.jpg  /7b3cLZjiOIR8pqjnF2g2GkBwcZ4.jpg
2  /whCG6TGm3h9AHBkfh5M0MnJ8zT0.jpg  /ker1eyGYk5eIIPiveZYGHaW9aZ5.jpg
3  /tN799oUR0f1gUKDYdMNrDaY7I51.jpg  /84FEpVVbSKYvKXDZJDZXOKBxCEm.jpg
4  /zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg  /c6BPbkO5Npt1OdwttAxCFo06wtH.jpg
5  /47XRWH95ATv4szxdWHl723guWXP.jpg  /wcUohmHc9oDZXarXDp905TYVui4.jpg
6  /92Tsfx7SFafOqWsotvrlJbHyehd.jpg  /lh3BDkmWJh998n4fQcHYcVi7dpm.jpg
7  /7EFwxOrBAiBRSl1YfGDTuLCExtR.jpg                               NaN
8  /s4dLRPJBUci4UjK7ujPbN9pwvgx.jpg                               NaN

  original_language belongs_to_collection_id                 created_at  \
0                en                     None 2026-08-24 21:38:46.531106
1                en                     None 2026-08-24 21:40:20.903623
2                en                     None 2026-08-24 21:43:39.802585
3                ko                     None 2026-08-24 18:39:16.796300
4                en                     None 2026-08-24 18:39:22.407567
5                de                     None 2026-08-24 18:39:31.748147
6                en                     None 2026-08-24 18:39:25.984922
7                pt                     None 2026-08-25 02:04:16.685508
8                pt                     None 2026-08-24 21:06:17.094435

                  updated_at
0 2026-08-24 21:38:48.882521
1 2026-08-24 21:40:22.217495
2 2026-08-24 21:43:43.863357
3 2026-08-24 19:18:13.835320
4 2026-08-25 10:52:55.099267
5 2026-08-25 07:05:26.461569
6 2026-08-25 00:48:25.543311
7 2026-08-25 02:04:17.513629
8 2026-08-24 21:06:18.067930

[9 rows x 23 columns]>

In [9]:
df.columns

Index(['movie_id', 'imdb_id', 'title', 'original_title', 'tagline', 'overview',
       'release_date', 'status', 'runtime', 'budget', 'revenue', 'popularity',
       'vote_average', 'vote_count', 'adult', 'video', 'homepage',
       'poster_path', 'backdrop_path', 'original_language',
       'belongs_to_collection_id', 'created_at', 'updated_at'],
      dtype='str')

In [28]:
df_display = df[['original_title', 'budget', 'revenue', 'release_date', 'poster_path']].copy()

df_display.head(2)

,original_title,budget,revenue,release_date,poster_path
0,Chicago,45000000,306776732,2002-12-10,/3ED8cWCXY9zkx77Sd0N5qMbsdDP.jpg
1,Copying Beethoven,11000000,6191746,2006-09-10,/xplAbPXhZF9B3H4OnhjQsEKUESe.jpg

In [29]:
from IPython.display import HTML

base_url = "https://image.tmdb.org/t/p/w500"

display(HTML(
    df_display.assign(
        poster_path=lambda x: x['poster_path'].apply(
            lambda p: f'<img src="{base_url}{p}" width="70">' if pd.notna(p) else ''
        )
    ).to_html(escape=False, index=False)
))

In [34]:
base_url = "https://image.tmdb.org/t/p/w500"

# 1. Create your subset dataframe
subset = df_display[['original_title', 'budget', 'revenue', 'release_date', 'poster_path']].copy()

# 2. Transform the poster path column into HTML images
subset['poster_path'] = subset['poster_path'].apply(
    lambda p: f'<img src="{base_url}{p}" width="70">' if pd.notna(p) else ''
)

# 3. Display it using HTML
display(HTML(subset.to_html(escape=False, index=False)))

In [36]:

# 1. Sort by revenue from highest to lowest and take the top 5
subset = df.sort_values(by='revenue', ascending=False)[['original_title', 'budget', 'revenue', 'release_date', 'poster_path']].head(5).copy()

# 2. Transform the poster path into HTML images
subset['poster_path'] = subset['poster_path'].apply(
    lambda p: f'<img src="{base_url}{p}" width="70">' if pd.notna(p) else ''
)

# 3. Display it using HTML
display(HTML(subset.to_html(escape=False, index=False)))